In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("abalone.csv", index_col=0)
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                 
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [14]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole_weight', 'Shucked_weight',
       'Viscera_weight', 'Shell_weight', 'Rings'],
      dtype='object')

In [15]:
df['Rings'].value_counts()

Rings
9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    103
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
27      2
24      2
1       1
26      1
29      1
2       1
25      1
Name: count, dtype: int64

In [17]:
unique_values = df['Sex'].unique()
unique_values

array(['M', 'F', 'I'], dtype=object)

In [19]:
sex_map = {'M': 0, 'F': 1,'I':2}
df['Sex'] = df['Sex'].apply(lambda x: sex_map[x])
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                  
0       0   0.455     0.365   0.095        0.5140          0.2245   
1       0   0.350     0.265   0.090        0.2255          0.0995   
2       1   0.530     0.420   0.135        0.6770          0.2565   
3       0   0.440     0.365   0.125        0.5160          0.2155   
4       2   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    1   0.565     0.450   0.165        0.8870          0.3700   
4173    0   0.590     0.440   0.135        0.9660          0.4390   
4174    0   0.600     0.475   0.205        1.1760          0.5255   
4175    1   0.625     0.485   0.150        1.0945          0.5310   
4176    0   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [20]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscera_weight    0
Shell_weight      0
Rings             0
dtype: int64

In [21]:
X=df.drop('Rings',axis=1)
X.head()

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                
0     0   0.455     0.365   0.095        0.5140          0.2245   
1     0   0.350     0.265   0.090        0.2255          0.0995   
2     1   0.530     0.420   0.135        0.6770          0.2565   
3     0   0.440     0.365   0.125        0.5160          0.2155   
4     2   0.330     0.255   0.080        0.2050          0.0895   

    Viscera_weight  Shell_weight  
id                                
0           0.1010         0.150  
1           0.0485         0.070  
2           0.1415         0.210  
3           0.1140         0.155  
4           0.0395         0.055

In [22]:
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                  
0       0   0.455     0.365   0.095        0.5140          0.2245   
1       0   0.350     0.265   0.090        0.2255          0.0995   
2       1   0.530     0.420   0.135        0.6770          0.2565   
3       0   0.440     0.365   0.125        0.5160          0.2155   
4       2   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    1   0.565     0.450   0.165        0.8870          0.3700   
4173    0   0.590     0.440   0.135        0.9660          0.4390   
4174    0   0.600     0.475   0.205        1.1760          0.5255   
4175    1   0.625     0.485   0.150        1.0945          0.5310   
4176    0   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [23]:
y=df['Rings']
y.value_counts()

Rings
9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    103
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
27      2
24      2
1       1
26      1
29      1
2       1
25      1
Name: count, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [26]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.24497607655502393
[[ 0  4  0  1  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 28  3  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 30 18  5  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 27 29 21 35  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6 10 51 63  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 30 83 30  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2 11 66 42 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2 11 44 44 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  4 38 36 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 21 14 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 15 10  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  7 11  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 

In [27]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.24976076555023924
[[ 0  0  0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 31  6  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25 26  8  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21 37 30 23  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5 15 57 53  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 10 33 71 34  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  8 18 45 47 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 15 36 40 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  8 31 32 19  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  4  9 24 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 11 14  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  5 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0

C:\Users\yosim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [28]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.2555023923444976
[[ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  8  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7 12 14  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  8 29 14  6  4  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  4 27 27 37 17  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  6 10 61 48 11  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 10 25 69 43  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  7  7 54 45 21  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  4  7 31 59 15  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  5 23 42 15  0  4  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  4 26 12  0  5  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  4 16  3  0  6  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3 10  5  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0

C:\Users\yosim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [29]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.17894736842105263
[[ 1  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  5  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  7 13  5  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  7 14 24 10  2  0  2  0  0  0  0  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  4 22 30 30 19  4  1  2  0  1  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  5 25 30 37 17 10  7  4  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2 12 26 38 30 16  9  9  2  2  3  1  1  0  0  1  0  0  0  0]
 [ 0  1  0  1 10 15 34 25 21 13 11  3  2  1  0  0  1  0  0  0  1  0  0]
 [ 0  1  0  1  1 12 25 30 14 10 12  6  1  1  3  4  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  8 19 24  9 10  9  2  2  1  1  2  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  7 10  6  8  7  7  1  0  0  0  1  2  1  1  0  0  0  0]
 [ 0  0  0  0  0  1  3  3  6  5  5  3  3  2  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  1  1  6  1  3  1  1  3  2  1  0  0  1  0  1  0  0  0  0]
 [ 0  0  0

In [30]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.24019138755980862
[[ 0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  7  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10 15 11  2  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  8 19 22  9  3  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 26 35 34 10  4  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  5 20 52 39 14  3  2  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  8 31 45 45 14  3  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  5 14 35 42 27  7  5  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  6 31 43 26  4  4  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  6 23 28 16  5  7  0  1  1  0  0  1  0  1  0  1  0  0]
 [ 0  0  0  0  0  4  6  8 16  8  3  3  0  0  1  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  6  6  6  2  2  2  2  3  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  3  5  7  2  2  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  2